import { JsonSchema } from '../llm/document-llm.port';
import { DocumentType } from './classifier';

/**
 * The shapes a document is allowed to come back as. Documents §12, §13, §14
 * for the per-type fields, §26 for the envelope they are assembled into.
 *
 * Two departures from the specification's worked examples, both deliberate:
 *
 *   Keys are camelCase where §26 prints `diagnoses_recorded` and
 *   `verification_status`. This JSON is stored in `PatientDocument.extraction`
 *   and handed to the mobile client verbatim, next to forty other camelCase
 *   response bodies. One snake_case island in the API is a worse outcome than a
 *   naming difference from an example, and the correspondence is exact:
 *   `diagnoses_recorded` → `diagnosesRecorded`, `follow_up` → `followUp`,
 *   `verification_status` → `verificationStatus`.
 *
 *   No `confidence` field is asked of the model. §26 shows one in the envelope
 *   and there is one in the stored result — but it is computed here, from
 *   evidence, not reported by the thing being measured. `document-llm.port.ts`
 *   has the benchmark.
 *
 * Every field is nullable and nothing is required beyond the arrays, because
 * the alternative to "this document did not say" is the model filling the slot.
 * §11: extract "without inventing missing values".
 */

export interface ExtractedMedication {
  name: string;
  strength: string | null;
  dose: string | null;
  frequency: string | null;
  route: string | null;
  duration: string | null;
  instructions: string | null;
  startDate: string | null;
  stopDate: string | null;
  /**
   * §12: "If handwriting or OCR quality makes a medication uncertain, the
   * system must mark it as uncertain instead of guessing." The model is asked
   * for this directly because it is the only party that saw the ambiguity.
   */
  uncertain: boolean;
}

export interface ExtractedInvestigation {
  test: string;
  result: string | null;
  unit: string | null;
  referenceRange: string | null;
  /**
   * Whatever the report itself printed — H, L, *, "high". Never derived here:
   * §13 permits surfacing a value that sits outside a stated range and forbids
   * diagnosing from it, and the line between those two is drawn by not being
   * the one who decided the value was abnormal.
   */
  flag: string | null;
  date: string | null;
}

export interface ExtractedDocument {
  /** What the document says about itself, not what the classifier decided. */
  document: {
    type: DocumentType;
    date: string | null;
    facility: string | null;
    author: string | null;
  };
  patient: {
    name: string | null;
    identifier: string | null;
  };
  medications: ExtractedMedication[];
  investigations: ExtractedInvestigation[];
  /**
   * §14: "The extracted diagnosis must be represented as: Diagnosis recorded in
   * the uploaded document. It must not be presented as a new diagnosis
   * generated by the AI." The field name is the reminder.
   */
  diagnosesRecorded: string[];
  procedures: string[];
  followUp: string[];
  allergies: string[];
  admission: {
    admittedOn: string | null;
    dischargedOn: string | null;
  } | null;
}

/** An empty result, so a failed or skipped extraction has a shape. */
export function emptyExtraction(type: DocumentType): ExtractedDocument {
  return {
    document: { type, date: null, facility: null, author: null },
    patient: { name: null, identifier: null },
    medications: [],
    investigations: [],
    diagnosesRecorded: [],
    procedures: [],
    followUp: [],
    allergies: [],
    admission: null,
  };
}

const nullableString = { type: ['string', 'null'] };

const MEDICATION_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    strength: nullableString,
    dose: nullableString,
    frequency: nullableString,
    route: nullableString,
    duration: nullableString,
    instructions: nullableString,
    startDate: nullableString,
    stopDate: nullableString,
    uncertain: { type: 'boolean' },
  },
  required: ['name', 'uncertain'],
};

const INVESTIGATION_SCHEMA = {
  type: 'object',
  properties: {
    test: { type: 'string' },
    result: nullableString,
    unit: nullableString,
    referenceRange: nullableString,
    flag: nullableString,
    date: nullableString,
  },
  required: ['test'],
};

const stringArray = { type: 'array', items: { type: 'string' } };

/**
 * The document-type-specific schemas §26 asks for.
 *
 * Narrow on purpose. A prescription schema with no `investigations` array is
 * not a missing feature; it is the constraint that stops a model that has been
 * asked for investigations from finding some, and a prescription always has
 * numbers on it that will serve if the schema insists.
 */
export function schemaFor(type: DocumentType): JsonSchema {
  const common = {
    documentDate: nullableString,
    facility: nullableString,
    patientName: nullableString,
  };

  switch (type) {
    case 'prescription':
      return {
        type: 'object',
        properties: {
          ...common,
          prescriber: nullableString,
          diagnosesRecorded: stringArray,
          medications: { type: 'array', items: MEDICATION_SCHEMA },
          followUp: stringArray,
          allergies: stringArray,
        },
        required: ['medications'],
      };

    case 'laboratory_report':
      return {
        type: 'object',
        properties: {
          ...common,
          orderedBy: nullableString,
          investigations: { type: 'array', items: INVESTIGATION_SCHEMA },
        },
        required: ['investigations'],
      };

    case 'discharge_summary':
      return {
        type: 'object',
        properties: {
          ...common,
          treatingPhysician: nullableString,
          admittedOn: nullableString,
          dischargedOn: nullableString,
          diagnosesRecorded: stringArray,
          procedures: stringArray,
          investigations: { type: 'array', items: INVESTIGATION_SCHEMA },
          medications: { type: 'array', items: MEDICATION_SCHEMA },
          followUp: stringArray,
          allergies: stringArray,
        },
        required: ['diagnosesRecorded'],
      };

    // Imaging reports, referral letters, consultation notes and anything a
    // reader called "other" share one schema. §33 puts richer imaging and
    // referral extraction past the MVP, and a schema invented ahead of the
    // documents it will meet is a schema that shapes the extraction to itself.
    default:
      return {
        type: 'object',
        properties: {
          ...common,
          author: nullableString,
          diagnosesRecorded: stringArray,
          procedures: stringArray,
          investigations: { type: 'array', items: INVESTIGATION_SCHEMA },
          medications: { type: 'array', items: MEDICATION_SCHEMA },
          followUp: stringArray,
          allergies: stringArray,
        },
        required: [],
      };
  }
}

/** What to tell the model it is doing, per document type. */
export function instructionFor(type: DocumentType): string {
  const rules = [
    'Copy values exactly as they appear. Do not translate, expand ' +
      'abbreviations, correct spellings or convert units.',
    'If a field is not present in the text, return null. Never guess a value ' +
      'and never infer one from another field.',
    'Do not add anything that is not written in the text.',
    'If the text for a medication is garbled or ambiguous, still return it ' +
      'and set "uncertain" to true rather than choosing the likeliest reading.',
    'Only list an allergy if the document actually names one. Do not write ' +
      '"none" or "nil" unless the document itself says so.',
  ];

  const opening: Record<string, string> = {
    prescription:
      'The text below was read by OCR from a printed prescription. Extract ' +
      'each prescribed medicine and the details written beside it.',
    laboratory_report:
      'The text below was read by OCR from a laboratory report. Rows are ' +
      'tab-separated: test name, result, unit, then the reference range. ' +
      'Extract one entry per test.',
    discharge_summary:
      'The text below was read by OCR from a hospital discharge summary. ' +
      'Extract the admission details, the diagnoses the document records, and ' +
      'what the patient was discharged on.',
  };

  const lead =
    opening[type] ??
    'The text below was read by OCR from a medical document. Extract whatever ' +
      'medical information it actually contains, and nothing else.';

  return `${lead}\n\n${rules.map((rule) => `- ${rule}`).join('\n')}`;
}
