/**
 * Centralised error codes.
 * Consumers (frontend, mobile) depend on these codes for i18n/handling.
 * NEVER change existing values — add new ones only.
 */
export const ErrorCodes = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVITATION_NOT_IMPLEMENTED: 'INVITATION_NOT_IMPLEMENTED',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',

  // Roles
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
  ROLE_SYSTEM_PROTECTED: 'ROLE_SYSTEM_PROTECTED',

  // Permissions
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',

  // Patients
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_MRN_TAKEN: 'PATIENT_MRN_TAKEN',

  // Appointments
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT',

  // Database
  DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
  DB_FOREIGN_KEY_CONSTRAINT: 'DB_FOREIGN_KEY_CONSTRAINT',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',

  // Rate limiting
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Billing
  BILLING_SERVICE_NOT_FOUND: 'BILLING_SERVICE_NOT_FOUND',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_BILLING_RESOURCE: 'INVALID_BILLING_RESOURCE',

  // Consultations
  CONSULTATION_NOT_FOUND: 'CONSULTATION_NOT_FOUND',

  // Inpatient
  WARD_NOT_FOUND: 'WARD_NOT_FOUND',
  BED_NOT_FOUND: 'BED_NOT_FOUND',
  ADMISSION_NOT_FOUND: 'ADMISSION_NOT_FOUND',
  BED_ALREADY_OCCUPIED: 'BED_ALREADY_OCCUPIED',
  BED_NOT_AVAILABLE: 'BED_NOT_AVAILABLE',
  INVALID_INPATIENT_RESOURCE: 'INVALID_INPATIENT_RESOURCE',
  DEATH_CERTIFICATE_NOT_FOUND: 'DEATH_CERTIFICATE_NOT_FOUND',

  // Integrations
  MACHINE_NOT_FOUND: 'MACHINE_NOT_FOUND',
  FILE_PARSING_FAILED: 'FILE_PARSING_FAILED',

  // Laboratory
  LAB_TEST_NOT_FOUND: 'LAB_TEST_NOT_FOUND',
  LAB_ORDER_NOT_FOUND: 'LAB_ORDER_NOT_FOUND',
  LAB_RESULT_NOT_FOUND: 'LAB_RESULT_NOT_FOUND',
  INVALID_LAB_RESOURCE: 'INVALID_LAB_RESOURCE',

  // Radiology
  RADIOLOGY_EXAM_NOT_FOUND: 'RADIOLOGY_EXAM_NOT_FOUND',
  RADIOLOGY_ORDER_NOT_FOUND: 'RADIOLOGY_ORDER_NOT_FOUND',
  RADIOLOGY_REPORT_NOT_FOUND: 'RADIOLOGY_REPORT_NOT_FOUND',
  INVALID_RADIOLOGY_RESOURCE: 'INVALID_RADIOLOGY_RESOURCE',
  S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',

  // Pharmacy
  DRUG_NOT_FOUND: 'DRUG_NOT_FOUND',
  PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  INVALID_PHARMACY_RESOURCE: 'INVALID_PHARMACY_RESOURCE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // Pre-Triage
  PRE_TRIAGE_NOT_FOUND: 'PRE_TRIAGE_NOT_FOUND',
  PRE_TRIAGE_ALREADY_CONVERTED: 'PRE_TRIAGE_ALREADY_CONVERTED',

  // Queue
  QUEUE_ITEM_NOT_FOUND: 'QUEUE_ITEM_NOT_FOUND',
  QUEUE_NUMBER_CONFLICT: 'QUEUE_NUMBER_CONFLICT',
  INVALID_QUEUE_STATUS: 'INVALID_QUEUE_STATUS',

  // Settings
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',

  // Patient portal
  //
  // Nothing here is reachable from `POST /patient-auth/claim`: that route
  // answers identically whether or not the MRN exists, so an error code is
  // itself a signal it must not send. Every code below is raised only against a
  // claim token the caller already holds.
  PATIENT_PORTAL_CLAIM_INVALID: 'PATIENT_PORTAL_CLAIM_INVALID',
  PATIENT_PORTAL_CLAIM_EXPIRED: 'PATIENT_PORTAL_CLAIM_EXPIRED',
  PATIENT_PORTAL_CLAIM_CONSUMED: 'PATIENT_PORTAL_CLAIM_CONSUMED',
  PATIENT_PORTAL_CLAIM_LOCKED: 'PATIENT_PORTAL_CLAIM_LOCKED',
  PATIENT_PORTAL_ALREADY_CLAIMED: 'PATIENT_PORTAL_ALREADY_CLAIMED',
  PATIENT_PORTAL_EMAIL_REQUIRED: 'PATIENT_PORTAL_EMAIL_REQUIRED',
  PATIENT_PORTAL_NOT_LINKED: 'PATIENT_PORTAL_NOT_LINKED',

  // Patient documents
  //
  // Nothing here reaches a patient as-is: the message beside the code is what
  // they read, and Documents §27 is explicit that it must be a sentence rather
  // than an engine's own words. The codes exist for the client to branch on —
  // a retake prompt looks different from a "wrong file type" prompt.
  PATIENT_DOCUMENT_NOT_FOUND: 'PATIENT_DOCUMENT_NOT_FOUND',
  PATIENT_DOCUMENT_UNSUPPORTED_TYPE: 'PATIENT_DOCUMENT_UNSUPPORTED_TYPE',
  PATIENT_DOCUMENT_UNREADABLE: 'PATIENT_DOCUMENT_UNREADABLE',
  PATIENT_DOCUMENT_PATIENT_REQUIRED: 'PATIENT_DOCUMENT_PATIENT_REQUIRED',
  PATIENT_DOCUMENT_SESSION_NOT_FOUND: 'PATIENT_DOCUMENT_SESSION_NOT_FOUND',
  PATIENT_DOCUMENT_NOT_READY: 'PATIENT_DOCUMENT_NOT_READY',
  /** A correction naming a value this document does not hold. */
  PATIENT_DOCUMENT_VALUE_NOT_FOUND: 'PATIENT_DOCUMENT_VALUE_NOT_FOUND',
  /** A correction the system could not read as one. Never stored as a guess. */
  PATIENT_DOCUMENT_CORRECTION_INVALID: 'PATIENT_DOCUMENT_CORRECTION_INVALID',

  // Object storage
  S3_SIGN_FAILED: 'S3_SIGN_FAILED',

  // Patient case taking
  //
  // `CASE_SESSION_NOT_FOUND` is returned both for a session that does not exist
  // and for one belonging to somebody else, for the same reason the portal
  // claim answers identically either way: two distinguishable answers make the
  // route an existence oracle.
  CASE_SESSION_NOT_FOUND: 'CASE_SESSION_NOT_FOUND',
  CASE_SESSION_NOT_IN_PROGRESS: 'CASE_SESSION_NOT_IN_PROGRESS',
  CASE_SESSION_CONSENT_REQUIRED: 'CASE_SESSION_CONSENT_REQUIRED',
  CASE_SESSION_ALREADY_SUBMITTED: 'CASE_SESSION_ALREADY_SUBMITTED',
  CASE_FACT_NOT_FOUND: 'CASE_FACT_NOT_FOUND',
  CASE_FACT_ALREADY_SUPERSEDED: 'CASE_FACT_ALREADY_SUPERSEDED',
  CASE_FIELD_UNKNOWN: 'CASE_FIELD_UNKNOWN',
  CASE_ANSWER_NOT_UNDERSTOOD: 'CASE_ANSWER_NOT_UNDERSTOOD',

  // Local AI
  //
  // One code for every sidecar capability, because the caller's move is the
  // same in each case: fall back to the path that does not need it. Which
  // capability failed is in the message, which is written to be shown.
  AI_SIDECAR_UNAVAILABLE: 'AI_SIDECAR_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
