/**
 * Centralised error codes.
 * Consumers (frontend, mobile) depend on these codes for i18n/handling.
 * NEVER change existing values — add new ones only.
 */
export const ErrorCodes = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',

  // Roles
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',

  // Permissions
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',

  // Patients
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_MRN_TAKEN: 'PATIENT_MRN_TAKEN',

  // Appointments
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT',

  // Database
  DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
  DB_FOREIGN_KEY_CONSTRAINT: 'DB_FOREIGN_KEY_CONSTRAINT',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',

  // Rate limiting
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Billing
  BILLING_SERVICE_NOT_FOUND: 'BILLING_SERVICE_NOT_FOUND',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_BILLING_RESOURCE: 'INVALID_BILLING_RESOURCE',

  // Consultations
  CONSULTATION_NOT_FOUND: 'CONSULTATION_NOT_FOUND',

  // Inpatient
  WARD_NOT_FOUND: 'WARD_NOT_FOUND',
  BED_NOT_FOUND: 'BED_NOT_FOUND',
  ADMISSION_NOT_FOUND: 'ADMISSION_NOT_FOUND',
  BED_ALREADY_OCCUPIED: 'BED_ALREADY_OCCUPIED',
  BED_NOT_AVAILABLE: 'BED_NOT_AVAILABLE',
  INVALID_INPATIENT_RESOURCE: 'INVALID_INPATIENT_RESOURCE',
  DEATH_CERTIFICATE_NOT_FOUND: 'DEATH_CERTIFICATE_NOT_FOUND',

  // Integrations
  MACHINE_NOT_FOUND: 'MACHINE_NOT_FOUND',
  FILE_PARSING_FAILED: 'FILE_PARSING_FAILED',

  // Laboratory
  LAB_TEST_NOT_FOUND: 'LAB_TEST_NOT_FOUND',
  LAB_ORDER_NOT_FOUND: 'LAB_ORDER_NOT_FOUND',
  LAB_RESULT_NOT_FOUND: 'LAB_RESULT_NOT_FOUND',
  INVALID_LAB_RESOURCE: 'INVALID_LAB_RESOURCE',

  // Radiology
  RADIOLOGY_EXAM_NOT_FOUND: 'RADIOLOGY_EXAM_NOT_FOUND',
  RADIOLOGY_ORDER_NOT_FOUND: 'RADIOLOGY_ORDER_NOT_FOUND',
  RADIOLOGY_REPORT_NOT_FOUND: 'RADIOLOGY_REPORT_NOT_FOUND',
  INVALID_RADIOLOGY_RESOURCE: 'INVALID_RADIOLOGY_RESOURCE',

  // Pharmacy
  DRUG_NOT_FOUND: 'DRUG_NOT_FOUND',
  PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  INVALID_PHARMACY_RESOURCE: 'INVALID_PHARMACY_RESOURCE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // Pre-Triage
  PRE_TRIAGE_NOT_FOUND: 'PRE_TRIAGE_NOT_FOUND',
  PRE_TRIAGE_ALREADY_CONVERTED: 'PRE_TRIAGE_ALREADY_CONVERTED',

  // Queue
  QUEUE_ITEM_NOT_FOUND: 'QUEUE_ITEM_NOT_FOUND',
  QUEUE_NUMBER_CONFLICT: 'QUEUE_NUMBER_CONFLICT',
  INVALID_QUEUE_STATUS: 'INVALID_QUEUE_STATUS',

  // Settings
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
