/**
 * RBAC Permission enum.
 * Format: RESOURCE_ACTION — makes permission checks readable.
 * Add new permissions here as modules are developed.
 */
export enum Permission {
  // Users
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Roles
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // Permissions
  PERMISSION_READ = 'PERMISSION_READ',
  PERMISSION_ASSIGN = 'PERMISSION_ASSIGN',

  // Patients
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_READ = 'PATIENT_READ',
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  PATIENT_DELETE = 'PATIENT_DELETE',

  // Appointments
  APPOINTMENT_CREATE = 'APPOINTMENT_CREATE',
  APPOINTMENT_READ = 'APPOINTMENT_READ',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  APPOINTMENT_DELETE = 'APPOINTMENT_DELETE',

  // Audit logs
  AUDIT_READ = 'AUDIT_READ',

  // Billing
  BILLING_CREATE = 'BILLING_CREATE',
  BILLING_READ = 'BILLING_READ',
  BILLING_UPDATE = 'BILLING_UPDATE',
  BILLING_DELETE = 'BILLING_DELETE',

  // Consultations
  CONSULTATION_CREATE = 'CONSULTATION_CREATE',
  CONSULTATION_READ = 'CONSULTATION_READ',
  CONSULTATION_UPDATE = 'CONSULTATION_UPDATE',
  CONSULTATION_DELETE = 'CONSULTATION_DELETE',

  // Inpatient
  INPATIENT_CREATE = 'INPATIENT_CREATE',
  INPATIENT_READ = 'INPATIENT_READ',
  INPATIENT_UPDATE = 'INPATIENT_UPDATE',
  INPATIENT_DELETE = 'INPATIENT_DELETE',

  // Integrations
  INTEGRATION_CREATE = 'INTEGRATION_CREATE',
  INTEGRATION_READ = 'INTEGRATION_READ',
  INTEGRATION_UPDATE = 'INTEGRATION_UPDATE',
  INTEGRATION_DELETE = 'INTEGRATION_DELETE',

  // Laboratory
  LABORATORY_CREATE = 'LABORATORY_CREATE',
  LABORATORY_READ = 'LABORATORY_READ',
  LABORATORY_UPDATE = 'LABORATORY_UPDATE',
  LABORATORY_DELETE = 'LABORATORY_DELETE',

  // Radiology
  RADIOLOGY_CREATE = 'RADIOLOGY_CREATE',
  RADIOLOGY_READ = 'RADIOLOGY_READ',
  RADIOLOGY_UPDATE = 'RADIOLOGY_UPDATE',
  RADIOLOGY_DELETE = 'RADIOLOGY_DELETE',

  // Pharmacy
  PHARMACY_CREATE = 'PHARMACY_CREATE',
  PHARMACY_READ = 'PHARMACY_READ',
  PHARMACY_UPDATE = 'PHARMACY_UPDATE',
  PHARMACY_DELETE = 'PHARMACY_DELETE',

  // Pre-Triage
  PRE_TRIAGE_CREATE = 'PRE_TRIAGE_CREATE',
  PRE_TRIAGE_READ = 'PRE_TRIAGE_READ',
  PRE_TRIAGE_UPDATE = 'PRE_TRIAGE_UPDATE',
  PRE_TRIAGE_DELETE = 'PRE_TRIAGE_DELETE',

  // Queue
  QUEUE_CREATE = 'QUEUE_CREATE',
  QUEUE_READ = 'QUEUE_READ',
  QUEUE_UPDATE = 'QUEUE_UPDATE',
  QUEUE_DELETE = 'QUEUE_DELETE',

  // Settings
  SETTINGS_READ = 'SETTINGS_READ',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',

  // Death Certificates
  DEATH_CERTIFICATE_CREATE = 'DEATH_CERTIFICATE_CREATE',
  DEATH_CERTIFICATE_READ = 'DEATH_CERTIFICATE_READ',
  DEATH_CERTIFICATE_UPDATE = 'DEATH_CERTIFICATE_UPDATE',
  DEATH_CERTIFICATE_DELETE = 'DEATH_CERTIFICATE_DELETE',
}
